import {FC, PropsWithChildren} from 'react'
import type { Metadata } from "next";
import "./globals.css";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

export const metadata: Metadata = {
  title: "Msbar test App",
  description: "Generated by create next app",
};


const Layout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <div className='flex flex-col'>
          <div className='bg-gray-400 px-6 py-2'>
            <h2 className='text-lg font-bold'>
              Msbar ERP
            </h2>
          </div>
          <div className='mt-2 py-2'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}

export default Layout;
